apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
data:
  Corefile: |
    shin.do:5353 {
        file /etc/coredns/shin.do.zone
        reload 10s
    }
    .:5353 {
        whoami
    }
  shin.do.zone: |
    $TTL	3600
    @	IN	SOA	ns1.shin.do.	root.shin.do. (
    				2021092102	; Serial
    				3600	; Refresh
    				900	; Retry
    				3600000 ; Expire
    				3600 ) 	; Minimum
    	IN	NS	ns1.shin.do.
    	IN	NS	ns2.shin.do.
    	IN	MX	10 ASPMX.L.GOOGLE.COM.
    	IN	MX	20 ALT1.ASPMX.L.GOOGLE.COM.
    	IN	MX	20 ALT2.ASPMX.L.GOOGLE.COM.
    	IN	MX	30 ASPMX2.GOOGLEMAIL.COM.
    	IN	MX	30 ASPMX3.GOOGLEMAIL.COM.
    	IN	MX	30 ASPMX4.GOOGLEMAIL.COM.
    	IN	MX	30 ASPMX5.GOOGLEMAIL.COM.
    ns1	IN	A	221.245.168.210
    ns2	IN	A	35.247.124.32
    google7adefcbf4c86cfef	IN	CNAME	google.com.
    blog	IN	A	221.245.168.211
    hoge  IN  A 99.99.99.106
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
spec:
  selector:
    matchLabels:
      app: coredns
  template:
    metadata:
      labels:
        app: coredns
    spec:
      containers:
      - name: coredns
        image: coredns/coredns:1.8.4
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
          readOnly: true
        ports:
        - containerPort: 5353
          name: dns
          protocol: UDP
      volumes:
        - name: config-volume
          configMap:
            name: coredns
            items:
            - key: Corefile
              path: Corefile
            - key: shin.do.zone
              path: shin.do.zone
---              
apiVersion: v1
kind: Service
metadata:
  name: coredns
spec:
  type: LoadBalancer
  selector:
    app: coredns
  ports:
  - name: dns
    port: 15353
    targetPort: 5353
    protocol: UDP
